# Generated by Django 3.2.7 on 2021-09-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelo',
            new_name='Sala',
        ),
    ]
