# Generated by Django 3.2.7 on 2021-09-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_modelo_sala'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sala',
            new_name='Modelo',
        ),
    ]
