# Generated by Django 3.2.7 on 2021-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_sala_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
