# Generated by Django 3.2.7 on 2021-09-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_modelo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='img',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
