# Generated by Django 3.2.7 on 2021-10-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='uso',
        ),
        migrations.AddField(
            model_name='modelo',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelo_habitacion', to='Home.categoria'),
        ),
    ]
